### ISSUE TITLE
Support results with more than 99 moves for Speed FMC

### ISSUE THREAD

**Issue by lgarron** [cubing/cubingcontests.com#17]
Some people at BASC 59 had over 99 moves for Speed FMC:

https://docs.google.com/spreadsheets/d/1RWEQo8jQeuZHz2mB5pDdZE2LWYA_TNdu2uUQgGlZv28/edit#gid=0

Unlike regular FMC, it doesn't take any longer to judge longer solutions, so I think this should be allowed. Further:

- 100 moves is a typical number of moves for a beginner, and I think there's still value in having them participate.
-  if someone makes a big mistake this still allows them *some* chance of recovery and at least get a full mean of 3.

**Comment by lgarron** [comment]
(I've entered such results as 99 for now.)

**Comment by dmint789** [comment]
What do you think the limit should be?

**Comment by lgarron** [comment]
I think 3 digits (999) would be a reasonable hard limit for now.

**Comment by dmint789** [comment]
Ok, I'll do that then
