### ISSUE TITLE
Mod Dashboard shows edit button for completed competitions, logs user out if clicked

### ISSUE THREAD

**Issue by TheMagicCuber** [cubing/cubingcontests.com#41]
https://github.com/user-attachments/assets/cd9f0620-174b-4ecd-802b-11a850ccbb6c

See video for explanation, but basically if I click "edit" on a competition that's already completed, it logs me out. Mentioned this to Deni and he said to post an issue here since the edit button shouldn't appear for non-admins.

**Comment by dmint789** [comment]
Yeah, so the current global behavior is to log you out whenever the server sends an unauthorized response. Would it be preferable to instead simply display an "Unauthorized" message and not log you out?

As for this specific bug, the edit button should simply be hidden once a contest is finished.

**Comment by dmint789** [comment]
@Ryau91 would you like to work on this one? At least hiding the edit button should be trivial.

**Comment by dmint789** [comment]
Also, all code related to disabling the inputs for mods after the contest is finished should be removed, since it wouldn't be doing anything anymore

**Comment by TheMagicCuber** [comment]
> Would it be preferable to instead simply display an "Unauthorized" message and not log you out?
> 
> As for this specific bug, the edit button should simply be hidden once a contest is finished.

I think displaying an unauthorized message would be better, since needing to log back in seems more tedious. Also yeah having the edit buttons be hidden post-results publish seems good to me
