### ISSUE TITLE
Time input changes on completion

### ISSUE THREAD

**Issue by kr-matthews** [cubing/cubingcontests.com#5]
When entering a time, it subtracts one day on completion:
![image](https://github.com/dmint789/cubing-contests/assets/49137025/eb7b705e-4359-481e-9e76-1e495a6ad319)
![image](https://github.com/dmint789/cubing-contests/assets/49137025/87f00c40-292d-4445-b3b9-0927c8207302)
It's also very annoying that you can't edit individual digits and need to backspace to the spot you want to edit.

**Comment by dmint789** [comment]
Most likely a time zone issue

**Comment by dmint789** [comment]
@kr-matthews the input has been updated. It now allows to move the cursor and erase any character, but I was unable to recreate the main issue with the date changing at the end. I tried to fix it, but I dunno if that will work on your end. Can you try again to see if the bug is still there? Would be best if you tested it at different times of day, 12 hours apart.

**Comment by kr-matthews** [comment]
Still not resolved at 20:00 UTC-8. I'll check tomorrow morning, but I'm pretty sure it's because the input creates a date at midnight UTC then displays it in my timezone (regardless of the current time of day).

Is this date at https://cubingcontests.com/records/extremebld displaying the correct day?
![image](https://github.com/dmint789/cubing-contests/assets/49137025/31fe2725-4970-4fe5-86ad-cf8e2d647229)

**Comment by dmint789** [comment]
> Is this date at https://cubingcontests.com/records/extremebld displaying the correct day?

Yes, the video was posted on that date. The issue seems to be isolated here. I'll have to look more into why this is happening.

**Comment by dmint789** [comment]
@kr-matthews I have finally figured out why this bug was happening and deployed a fix. Can you please confirm the result submission form date bug is fixed?

**Comment by kr-matthews** [comment]
Seems to be fixed; if I type 02022012 then it stays as 02.02.2012, and I can edit the string at any position.

**Comment by dmint789** [comment]
Great! Thanks for confirming that
